package com.sol.quizzapp.domain.model.flags

enum class Countries(val code: String, val title: String) {
    AFGHANISTAN("AF", "Afghanistan"),
    ALBANIA("AL", "Albania"),
    ALGERIA("DZ", "Algeria"),
    ANDORRA("AD", "Andorra"),
    AMERICAN_SAMOA("AS", "American Samoa"),
    ANGOLA("AO", "Angola"),
    ANGUILLA("AI", "Anguilla"),
    ANTARCTICA("AQ", "Antarctica"),
    ANTIGUA_AND_BARBUDA("AG", "Antigua and Barbuda"),
    ARGENTINA("AR", "Argentina"),
    ARMENIA("AM", "Armenia"),
    ARUBA("AW", "Aruba"),
    AUSTRALIA("AU", "Australia"),
    AUSTRIA("AT", "Austria"),
    AZERBAIJAN("AZ", "Azerbaijan"),
    BAHAMAS("BS", "Bahamas"),
    BAHRAIN("BH", "Bahrain"),
    BANGLADESH("BD", "Bangladesh"),
    BARBADOS("BB", "Barbados"),
    BELARUS("BY", "Belarus"),
    BELGIUM("BE", "Belgium"),
    BELIZE("BZ", "Belize"),
    BENIN("BJ", "Benin"),
    BERMUDA("BF", "Bermuda"),
    BHUTAN("BT", "Bhutan"),
    BOLIVIA("BO", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bosnia and Herzegovina"),
    BOTSWANA("BW", "Botswana"),
    BRAZIL("BR", "Brazil"),
    BRUNEI("BN", "Brunei"),
    BULGARIA("BG", "Bulgaria"),
    BURKINA_FASO("BF", "Burkina Faso"),
    BURUNDI("BI", "Burundi"),
    CABO_VERDE("CV", "Cabo Verde"),
    CAMBODIA("KH", "Cambodia"),
    CAMEROON("CM", "Cameroon"),
    CANADA("CA", "Canada"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "Central African Republic"),
    CHAD("TD", "Chad"),
    CHILE("CL", "Chile"),
    CHINA("CN", "China"),
    COCOS_ISLANDS("CC", "Cocos Islands"),
    COLOMBIA("CO", "Colombia"),
    COMOROS("KM", "Comoros"),
    CONGO("CG", "Congo"),
    COOK_ISLANDS("CK", "Cook Islands"),
    CROATIA("HR", "Croatia"),
    COSTA_RICA("CR", "Costa Rica"),
    CUBA("CU", "Cuba"),
    CYPRUS("CY", "Cyprus"),
    CZECH_REPUBLIC("CZ", "Czech Republic"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("CD", "Democratic Republic of the Congo"),
    DENMARK("DK", "Denmark"),
    DJIBOUTI("DJ", "Djibouti"),
    DOMINICA("DM", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "Dominican Republic"),
    EAST_TIMOR("TL", "East Timor"),
    ECUADOR("EC", "Ecuador"),
    EGYPT("EG", "Egypt"),
    EL_SALVADOR("SV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "Equatorial Guinea"),
    ERITREA("ER", "Eritrea"),
    ESTONIA("EE", "Estonia"),
    ESWATINI("SZ", "Eswatini"),
    ETHIOPIA("ET", "Ethiopia"),
    FALKLAND_ISLANDS("FK", "Falkland Islands (Malvinas)"),
    FAROE_ISLANDS("FO", "Faroe Islands"),
    FIJI("FJ", "Fiji"),
    FINLAND("FI", "Finland"),
    FRANCE("FR", "France"),
    FRENCH_POLYNESIA("PF", "French Polynesia"),
    GABON("GA", "Gabon"),
    GAMBIA("GM", "Gambia"),
    GEORGIA("GE", "Georgia"),
    GERMANY("DE", "Germany"),
    GHANA("GH", "Ghana"),
    GIBRALTAR("GI", "Gibraltar"),
    GREECE("GR", "Greece"),
    GREENLAND("GL", "Greenland"),
    GRENADA("GD", "Grenada"),
    GUAM("GU", "Guam"),
    GUATEMALA("GT", "Guatemala"),
    GUERNSEY("GG", "Guernsey"),
    GUINEA("GN", "Guinea"),
    GUINEA_BISSAU("GW", "Guinea-Bissau"),
    GUYANA("GY", "Guyana"),
    HAITI("HT", "Haiti"),
    HONDURAS("HN", "Honduras"),
    HONG_KONG("HK", "Hong Kong"),
    HUNGARY("HU", "Hungary"),
    ICELAND("IS", "Iceland"),
    INDIA("IN", "India"),
    INDONESIA("ID", "Indonesia"),
    IRAN("IR", "Iran"),
    IRAQ("IQ", "Iraq"),
    IRELAND("IE", "Ireland"),
    ISLE_OF_MAN("IM", "Isle of Man"),
    ISRAEL("IL", "Israel"),
    ITALY("IT", "Italy"),
    IVORY_COAST("CI", "Ivory Coast"),
    JAMAICA("JM", "Jamaica"),
    JAPAN("JP", "Japan"),
    JERSEY("JE", "Jersey"),
    JORDAN("JO", "Jordan"),
    KAZAKHSTAN("KZ", "Kazakhstan"),
    KENYA("KE", "Kenya"),
    KIRIBATI("KI", "Kiribati"),
    KUWAIT("KW", "Kuwait"),
    KYRGYZSTAN("KG", "Kyrgyzstan"),
    LAOS("LA", "Laos"),
    LESOTHO("LS", "Lesotho"),
    LATVIA("LV", "Latvia"),
    LEBANON("LB", "Lebanon"),
    LIBERIA("LR", "Liberia"),
    LIBYA("LY", "Libya"),
    LIECHTENSTEIN("LI", "Liechtenstein"),
    LITHUANIA("LT", "Lithuania"),
    LUXEMBOURG("LU", "Luxembourg"),
    MACAU("MO", "Macau"),
    NORTH_MACEDONIA("MK", "North Macedonia"),
    MADAGASCAR("MG", "Madagascar"),
    MALAYSIA("MY", "Malaysia"),
    MALAWI("MW", "Malawi"),
    MALDIVES("MV", "Maldives"),
    MALI("ML", "Mali"),
    MALTA("MT", "Malta"),
    MOROCCO("MA", "Morocco"),
    MARSHALL_ISLAND("MH", "Marshall Islands"),
    MARTINIQUE("MQ", "Martinique"),
    MAURITIUS("MU", "Mauritius"),
    MAURITANIA("MR", "Mauritania"),
    MAYOTTE("YT", "Mayotte"),
    MEXICO("MX", "Mexico"),
    MICRONESIA("FM", "Micronesia"),
    MOLDOVA("MD", "Moldova"),
    MONACO("MC", "Monaco"),
    MONGOLIA("MN", "Mongolia"),
    MONTENEGRO("ME", "Montenegro"),
    MONTSERRAT("MS", "Montserrat"),
    MOZAMBIQUE("MZ", "Mozambique"),
    MYANMAR("MM", "Myanmar"),
    NAMIBIA("NA", "Namibia"),
    NAURU("NR", "Nauru"),
    NEPAL("NP", "Nepal"),
    NETHERLANDS_ANTILLES("AN", "Netherlands Antilles"),
    NEW_CALEDONIA("NC", "New Caledonia"),
    NEW_ZEALAND("NZ", "New Zealand"),
    NICARAGUA("NI", "Nicaragua"),
    NIGER("NE", "Niger"),
    NIGERIA("NG", "Nigeria"),
    NIUE("NU", "Niue"),
    NORFOLK_ISLAND("NF", "Norfolk Island"),
    NORTH_KOREA("KP", "North Korea"),
    NORTHERN_MARIANA_ISLANDS("MP", "Northern Mariana Islands"),
    NORWAY("NO", "Norway"),
    OMAN("OM", "Oman"),
    NETHERLANDS("NL", "Netherlands"),
    PAKISTAN("PK", "Pakistan"),
    PALAU("PW", "Palau"),
    PALESTINE("PS", "Palestine"),
    PANAMA("PA", "Panama"),
    PAPUA_NEW_GUINEA("PG", "Papua New Guinea"),
    PARAGUAY("PY", "Paraguay"),
    PERU("PE", "Peru"),
    PHILIPPINES("PH", "Philippines"),
    PITCAIRN("PN", "Pitcairn"),
    POLAND("PL", "Poland"),
    PORTUGAL("PT", "Portugal"),
    PUERTO_RICO("PR", "Puerto Rico"),
    QATAR("QA", "Qatar"),
    REUNION("RE", "Réunion"),
    ROMANIA("RO", "Romania"),
    RUSSIA("RU", "Russia"),
    RWANDA("RW", "Rwanda"),
    SAINT_BARTHELEMY("BL", "Saint Barthelemy"),
    SAINT_HELENA("SH", "Saint Helena"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts and Nevis"),
    SAINT_MARTIN("MF", "Saint Martin"),
    SAINT_PIERRE_AND_MIQUELON("PM", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent and the Grenadines"),
    SAINT_LUCIA("LC", "Saint Lucia"),
    SAMOA("WS", "Samoa"),
    SAN_MARINO("SM", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "Sao Tome and Principe"),
    SAUDI_ARABIA("SA", "Saudi Arabia"),
    SENEGAL("SN", "Senegal"),
    SERBIA("RS", "Serbia"),
    SEYCHELLES("SC", "Seychelles"),
    SIERRA_LEONE("SL", "Sierra Leone"),
    SINGAPORE("SG", "Singapore"),
    SLOVAKIA("SK", "Slovakia"),
    SLOVENIA("SI", "Slovenia"),
    SOLOMON_ISLANDS("SB", "Solomon Islands"),
    SYRIA("SY", "Syria"),
    SOMALIA("SO", "Somalia"),
    SRI_LANKA("LK", "Sri Lanka"),
    SUDAN("SD", "Sudan"),
    SOUTH_AFRICA("ZA", "South Africa"),
    SOUTH_KOREA("KR", "South Korea"),
    SOUTH_SUDAN("SS", "South Sudan"),
    SURINAME("SR", "Suriname"),
    SWEDEN("SE", "Sweden"),
    SWITZERLAND("CH", "Switzerland"),
    THAILAND("TH", "Thailand"),
    TAIWAN("TW", "Taiwan"),
    TANZANIA("TZ", "Tanzania"),
    TAJIKISTAN("TJ", "Tajikistan"),
    TOGO("TG", "Togo"),
    TOKELAU("TK", "Tokelau"),
    TONGA("TO", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "Trinidad and Tobago"),
    TUNISIA("TN", "Tunisia"),
    TURKMENISTAN("TM", "Turkmenistan"),
    TURKEY("TR", "Turkey"),
    TURKS_AND_CAICOS_ISLANDS("TC", "Turks and Caicos Islands"),
    TUVALU("TV", "Tuvalu"),
    UGANDA("UG", "Uganda"),
    UKRAINE("UA", "Ukraine"),
    UNITED_KINGDOM("GB", "United Kingdom"),
    UNITED_STATES("US", "United States"),
    URUGUAY("UY", "Uruguay"),
    UZBEKISTAN("UZ", "Uzbekistan"),
    VANUATU("VU", "Vanuatu"),
    VATICAN("VA", "Vatican"),
    VENEZUELA("VE", "Venezuela"),
    VIETNAM("VN", "Vietnam"),
    VIRGIN_ISLANDS_BRITISH("VG", "Virgin Islands, British"),
    VIRGIN_ISLANDS_US("VI", "Virgin Islands, U.S"),
    WALLIS_AND_FUTUNA("WF", "Wallis and Futuna"),
    WESTERN_SAHARA("EH", "Western Sahara"),
    YEMEN("YE", "Yemen"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABWE("ZW", "Zimbabwe");
}

data class Question(
    val correctCountry: Countries,
    val options: List<Countries>
)