package com.sol.quizzapp.domain.model.logo

enum class Company(
    val title: String,
    val domain: String,
    val category: String
) {
    GOOGLE("Google", "google.com", "Technology"),
    APPLE("Apple", "apple.com", "Technology"),
    MICROSOFT("Microsoft", "microsoft.com", "Technology"),
    AMAZON("Amazon", "amazon.com", "E-commerce"),
    FACEBOOK("Facebook", "facebook.com", "Social Media"),
    TESLA("Tesla", "tesla.com", "Automotive"),
    NETFLIX("Netflix", "netflix.com", "Entertainment"),
    DISNEY("Disney", "disney.com", "Entertainment"),
    SAMSUNG("Samsung", "samsung.com", "Electronics"),
    NIKE("Nike", "nike.com", "Fashion"),
    ADIDAS("Adidas", "adidas.com", "Fashion"),
    COCA_COLA("Coca-Cola", "coca-cola.com", "Beverages"),
    PEPSI("Pepsi", "pepsi.com", "Beverages"),
    STARBUCKS("Starbucks", "starbucks.com", "Hospitality"),
    MCDONALDS("McDonald's", "mcdonalds.com", "Food & Beverage"),
    BURGER_KING("Burger King", "burgerking.com", "Food & Beverage"),
    KFC("KFC", "kfc.com", "Food & Beverage"),
    TOYOTA("Toyota", "toyota.com", "Automotive"),
    BMW("BMW", "bmw.com", "Automotive"),
    MERCEDES("Mercedes-Benz", "mercedes-benz.com", "Automotive"),
    AUDI("Audi", "audi.com", "Automotive"),
    PORSCHE("Porsche", "porsche.com", "Automotive"),
    VISA("Visa", "visa.com", "Finance"),
    MASTERCARD("Mastercard", "mastercard.com", "Finance"),
    PAYPAL("PayPal", "paypal.com", "Finance"),
    SQUARE("Square", "square.com", "Finance"),
    SPOTIFY("Spotify", "spotify.com", "Entertainment"),
    YOUTUBE("YouTube", "youtube.com", "Entertainment"),
    TWITTER("Twitter", "twitter.com", "Social Media"),
    INSTAGRAM("Instagram", "instagram.com", "Social Media"),
    LINKEDIN("LinkedIn", "linkedin.com", "Social Media"),
    SNAPCHAT("Snapchat", "snapchat.com", "Social Media"),
    PINTEREST("Pinterest", "pinterest.com", "Social Media"),
    TIKTOK("TikTok", "tiktok.com", "Social Media"),
    UBER("Uber", "uber.com", "Transportation"),
    LYFT("Lyft", "lyft.com", "Transportation"),
    AIRBNB("Airbnb", "airbnb.com", "Hospitality"),
    BOOKING("Booking", "booking.com", "Travel"),
    EXPEDIA("Expedia", "expedia.com", "Travel"),
    DELTA("Delta Airlines", "delta.com", "Aviation"),
    UNITED("United Airlines", "united.com", "Aviation"),
    AMERICAN_AIRLINES("American Airlines", "aa.com", "Aviation"),
    BOEING("Boeing", "boeing.com", "Aerospace"),
    LOCKHEED_MARTIN("Lockheed Martin", "lockheedmartin.com", "Defense"),
    GENERAL_ELECTRIC("General Electric", "ge.com", "Industrial"),
    JOHNSON_JOHNSON("Johnson & Johnson", "jnj.com", "Healthcare"),
    PFIZER("Pfizer", "pfizer.com", "Pharmaceuticals"),
    MODERNA("Moderna", "modernatx.com", "Pharmaceuticals"),
    GSK("GSK", "gsk.com", "Pharmaceuticals"),
    ASTRAZENECA("AstraZeneca", "astrazeneca.com", "Pharmaceuticals"),
    MERCK("Merck", "merck.com", "Pharmaceuticals"),
    NOVARTIS("Novartis", "novartis.com", "Pharmaceuticals"),
    IBM("IBM", "ibm.com", "Technology"),
    INTEL("Intel", "intel.com", "Technology"),
    NVIDIA("NVIDIA", "nvidia.com", "Technology"),
    AMD("AMD", "amd.com", "Technology"),
    QUALCOMM("Qualcomm", "qualcomm.com", "Technology"),
    HP("HP", "hp.com", "Electronics"),
    DELL("Dell", "dell.com", "Electronics"),
    ASUS("ASUS", "asus.com", "Electronics"),
    LENOVO("Lenovo", "lenovo.com", "Electronics"),
    HUAWEI("Huawei", "huawei.com", "Electronics"),
    XIAOMI("Xiaomi", "mi.com", "Electronics"),
    OPPO("Oppo", "oppo.com", "Electronics"),
    VIVO("Vivo", "vivo.com", "Electronics"),
    PHILIPS("Philips", "philips.com", "Electronics"),
    PANASONIC("Panasonic", "panasonic.com", "Electronics"),
    SONY("Sony", "sony.com", "Electronics"),
    LG("LG", "lg.com", "Electronics"),
    RED_BULL("Red Bull", "redbull.com", "Beverages"),
    MONSTER("Monster", "monsterenergy.com", "Beverages"),
    GUCCI("Gucci", "gucci.com", "Fashion"),
    PRADA("Prada", "prada.com", "Fashion"),
    LOUIS_VUITTON("Louis Vuitton", "louisvuitton.com", "Fashion"),
    ZARA("Zara", "zara.com", "Fashion"),
    H_M("H&M", "hm.com", "Fashion"),
    UNIQLO("Uniqlo", "uniqlo.com", "Fashion"),
    IKEA("IKEA", "ikea.com", "Furniture"),
    WALMART("Walmart", "walmart.com", "Retail"),
    TARGET("Target", "target.com", "Retail"),
    COSTCO("Costco", "costco.com", "Retail"),
    HOME_DEPOT("Home Depot", "homedepot.com", "Retail"),
    BEST_BUY("Best Buy", "bestbuy.com", "Retail"),
    CVS("CVS", "cvs.com", "Healthcare"),
    WALGREENS("Walgreens", "walgreens.com", "Healthcare"),
    LOWES("Lowe's", "lowes.com", "Retail"),
    SHELL("Shell", "shell.com", "Energy"),
    EXXON_MOBIL("ExxonMobil", "exxonmobil.com", "Energy"),
    BP("BP", "bp.com", "Energy"),
    CHEVRON("Chevron", "chevron.com", "Energy"),
    TOTAL("Total", "total.com", "Energy"),
    ARAMCO("Saudi Aramco", "aramco.com", "Energy"),
    ALPHABET("Alphabet", "abc.xyz", "Technology"),
    ORACLE("Oracle", "oracle.com", "Technology"),
    SAP("SAP", "sap.com", "Technology"),
    ADOBE("Adobe", "adobe.com", "Technology"),
    SALESFORCE("Salesforce", "salesforce.com", "Technology"),
    TENCENT("Tencent", "tencent.com", "Technology"),
    BYTEDANCE("ByteDance", "bytedance.com", "Technology"),
    BAIDU("Baidu", "baidu.com", "Technology"),
    ALIBABA("Alibaba", "alibaba.com", "E-commerce"),
    JD("JD.com", "jd.com", "E-commerce"),
    EBAY("eBay", "ebay.com", "E-commerce"),
    SHOPIFY("Shopify", "shopify.com", "E-commerce"),
    RAKUTEN("Rakuten", "rakuten.com", "E-commerce"),
    FLIPKART("Flipkart", "flipkart.com", "E-commerce"),
    WALGREENS_BOOTS("Walgreens Boots Alliance", "walgreensbootsalliance.com", "Healthcare"),
    CVS_HEALTH("CVS Health", "cvshealth.com", "Healthcare"),
    ABBOTT("Abbott Laboratories", "abbott.com", "Healthcare"),
    ROCHE("Roche", "roche.com", "Pharmaceuticals"),
    SANOFI("Sanofi", "sanofi.com", "Pharmaceuticals"),
    BAYER("Bayer", "bayer.com", "Pharmaceuticals"),
    BRISTOL_MYERS("Bristol-Myers Squibb", "bms.com", "Pharmaceuticals"),
    AMGEN("Amgen", "amgen.com", "Pharmaceuticals"),
    REGENERON("Regeneron", "regeneron.com", "Pharmaceuticals"),
    BIOGEN("Biogen", "biogen.com", "Pharmaceuticals"),
    BLACKROCK("BlackRock", "blackrock.com", "Finance"),
    GOLDMAN_SACHS("Goldman Sachs", "goldmansachs.com", "Finance"),
    JPMORGAN("JPMorgan Chase", "jpmorganchase.com", "Finance"),
    MORGAN_STANLEY("Morgan Stanley", "morganstanley.com", "Finance"),
    WELLS_FARGO("Wells Fargo", "wellsfargo.com", "Finance"),
    BANK_OF_AMERICA("Bank of America", "bankofamerica.com", "Finance"),
    CITI("Citigroup", "citi.com", "Finance"),
    BARCLAYS("Barclays", "barclays.com", "Finance"),
    HSBC("HSBC", "hsbc.com", "Finance"),
    DEUTSCHE_BANK("Deutsche Bank", "db.com", "Finance"),
    UBS("UBS", "ubs.com", "Finance"),
    CREDIT_SUISSE("Credit Suisse", "credit-suisse.com", "Finance"),
    SOFI("SoFi", "sofi.com", "Finance"),
    ROBINHOOD("Robinhood", "robinhood.com", "Finance"),
    COINBASE("Coinbase", "coinbase.com", "Cryptocurrency"),
    BINANCE("Binance", "binance.com", "Cryptocurrency"),
    KRAKEN("Kraken", "kraken.com", "Cryptocurrency"),
    OPENSEA("OpenSea", "opensea.io", "NFTs"),
    RIOT_GAMES("Riot Games", "riotgames.com", "Gaming"),
    ACTIVISION("Activision Blizzard", "activisionblizzard.com", "Gaming"),
    UBISOFT("Ubisoft", "ubisoft.com", "Gaming"),
    ELECTRONIC_ARTS("Electronic Arts", "ea.com", "Gaming"),
    SONY_PLAYSTATION("Sony PlayStation", "playstation.com", "Gaming"),
    NINTENDO("Nintendo", "nintendo.com", "Gaming"),
    SEGA("SEGA", "sega.com", "Gaming"),
    EPIC_GAMES("Epic Games", "epicgames.com", "Gaming"),
    VALVE("Valve", "valvesoftware.com", "Gaming"),
    STEAM("Steam", "store.steampowered.com", "Gaming"),
    PARADOX("Paradox Interactive", "paradoxinteractive.com", "Gaming"),
    CD_PROJEKT("CD Projekt", "cdprojekt.com", "Gaming"),
    TSMC("TSMC", "tsmc.com", "Semiconductors"),
    ARM("ARM", "arm.com", "Semiconductors"),
    BROADCOM("Broadcom", "broadcom.com", "Semiconductors"),
    TEXAS_INSTRUMENTS("Texas Instruments", "ti.com", "Semiconductors"),
    ST_MICROELECTRONICS("STMicroelectronics", "st.com", "Semiconductors"),
    INFINEON("Infineon", "infineon.com", "Semiconductors"),
    MICROCHIP("Microchip Technology", "microchip.com", "Semiconductors"),
    WESTERN_DIGITAL("Western Digital", "westerndigital.com", "Data Storage"),
    SEAGATE("Seagate", "seagate.com", "Data Storage"),
    KINGSTON("Kingston Technology", "kingston.com", "Data Storage"),
    SANDISK("SanDisk", "sandisk.com", "Data Storage"),
    DROPBOX("Dropbox", "dropbox.com", "Cloud Storage"),
    BOX("Box", "box.com", "Cloud Storage"),
    ZOOM("Zoom", "zoom.us", "Communication"),
    SLACK("Slack", "slack.com", "Communication"),
    SKYPE("Skype", "skype.com", "Communication"),
    CISCO("Cisco", "cisco.com", "Networking"),
    NOKIA("Nokia", "nokia.com", "Networking"),
    ERICSSON("Ericsson", "ericsson.com", "Networking"),
    VERIZON("Verizon", "verizon.com", "Telecom"),
    AT_T("AT&T", "att.com", "Telecom"),
    T_MOBILE("T-Mobile", "t-mobile.com", "Telecom"),
    VODAFONE("Vodafone", "vodafone.com", "Telecom"),
    ORANGE("Orange", "orange.com", "Telecom"),
    DELOITTE("Deloitte", "deloitte.com", "Consulting"),
    EY("Ernst & Young", "ey.com", "Consulting"),
    KPMG("KPMG", "kpmg.com", "Consulting"),
    PWC("PwC", "pwc.com", "Consulting"),
    BCG("Boston Consulting Group", "bcg.com", "Consulting"),
    MCKINSEY("McKinsey & Company", "mckinsey.com", "Consulting"),
    BAIN("Bain & Company", "bain.com", "Consulting"),
    SPECTRUM("Spectrum", "spectrum.com", "Telecom"),
    HERSHEY("Hershey", "hersheys.com", "Food"),
    MARS("Mars", "mars.com", "Food"),
    FERRERO("Ferrero", "ferrero.com", "Food"),
    KELLOGG("Kellogg's", "kelloggs.com", "Food"),
    GENERAL_MILLS("General Mills", "generalmills.com", "Food"),
    UNILEVER("Unilever", "unilever.com", "Consumer Goods"),
    PROCTER_GAMBLE("Procter & Gamble", "pg.com", "Consumer Goods"),
    ;
}

data class QuestionCompany(
    val correctCompany: Company,
    val options: List<Company>
)