package com.sol.quizzapp.domain.model.logo

enum class Company(
    val title: String,
    val domain: String,
    val category: String
) {
    GOOGLE("Google", "google.com", "Technology"),
    APPLE("Apple", "apple.com", "Technology"),
    MICROSOFT("Microsoft", "microsoft.com", "Technology"),
    AMAZON("Amazon", "amazon.com", "E-commerce"),
    FACEBOOK("Facebook", "facebook.com", "Social Media"),
    TESLA("Tesla", "tesla.com", "Automotive"),
    NETFLIX("Netflix", "netflix.com", "Entertainment"),
    DISNEY("Disney", "disney.com", "Entertainment"),
    SAMSUNG("Samsung", "samsung.com", "Electronics"),
    NIKE("Nike", "nike.com", "Fashion"),
    ADIDAS("Adidas", "adidas.com", "Fashion"),
    COCA_COLA("Coca-Cola", "coca-cola.com", "Beverages"),
    PEPSI("Pepsi", "pepsi.com", "Beverages"),
    STARBUCKS("Starbucks", "starbucks.com", "Hospitality"),
    MCDONALDS("McDonald's", "mcdonalds.com", "Food & Beverage"),
    BURGER_KING("Burger King", "burgerking.com", "Food & Beverage"),
    KFC("KFC", "kfc.com", "Food & Beverage"),
    TOYOTA("Toyota", "toyota.com", "Automotive"),
    BMW("BMW", "bmw.com", "Automotive"),
    MERCEDES("Mercedes-Benz", "mercedes-benz.com", "Automotive"),
    AUDI("Audi", "audi.com", "Automotive"),
    PORSCHE("Porsche", "porsche.com", "Automotive"),
    VISA("Visa", "visa.com", "Finance"),
    MASTERCARD("Mastercard", "mastercard.com", "Finance"),
    PAYPAL("PayPal", "paypal.com", "Finance"),
    SQUARE("Square", "square.com", "Finance"),
    SPOTIFY("Spotify", "spotify.com", "Entertainment"),
    YOUTUBE("YouTube", "youtube.com", "Entertainment"),
    TWITTER("Twitter", "twitter.com", "Social Media"),
    INSTAGRAM("Instagram", "instagram.com", "Social Media"),
    LINKEDIN("LinkedIn", "linkedin.com", "Social Media"),
    SNAPCHAT("Snapchat", "snapchat.com", "Social Media"),
    PINTEREST("Pinterest", "pinterest.com", "Social Media"),
    TIKTOK("TikTok", "tiktok.com", "Social Media"),
    AIRBNB("Airbnb", "airbnb.com", "Hospitality"),
    BOOKING("Booking", "booking.com", "Travel"),
    EXPEDIA("Expedia", "expedia.com", "Travel"),
    DELTA("Delta Airlines", "delta.com", "Aviation"),
    UNITED("United Airlines", "united.com", "Aviation"),
    AMERICAN_AIRLINES("American Airlines", "aa.com", "Aviation"),
    GENERAL_ELECTRIC("General Electric", "ge.com", "Industrial"),
    JOHNSON_JOHNSON("Johnson & Johnson", "jnj.com", "Healthcare"),
    PFIZER("Pfizer", "pfizer.com", "Pharmaceuticals"),
    MODERNA("Moderna", "modernatx.com", "Pharmaceuticals"),
    GSK("GSK", "gsk.com", "Pharmaceuticals"),
    ASTRAZENECA("AstraZeneca", "astrazeneca.com", "Pharmaceuticals"),
    MERCK("Merck", "merck.com", "Pharmaceuticals"),
    NOVARTIS("Novartis", "novartis.com", "Pharmaceuticals"),
    IBM("IBM", "ibm.com", "Technology"),
    INTEL("Intel", "intel.com", "Technology"),
    NVIDIA("NVIDIA", "nvidia.com", "Technology"),
    AMD("AMD", "amd.com", "Technology"),
    QUALCOMM("Qualcomm", "qualcomm.com", "Technology"),
    HP("HP", "hp.com", "Electronics"),
    DELL("Dell", "dell.com", "Electronics"),
    ASUS("ASUS", "asus.com", "Electronics"),
    LENOVO("Lenovo", "lenovo.com", "Electronics"),
    HUAWEI("Huawei", "huawei.com", "Electronics"),
    XIAOMI("Xiaomi", "mi.com", "Electronics"),
    OPPO("Oppo", "oppo.com", "Electronics"),
    VIVO("Vivo", "vivo.com", "Electronics"),
    PHILIPS("Philips", "philips.com", "Electronics"),
    PANASONIC("Panasonic", "panasonic.com", "Electronics"),
    SONY("Sony", "sony.com", "Electronics"),
    LG("LG", "lg.com", "Electronics"),
    RED_BULL("Red Bull", "redbull.com", "Beverages"),
    MONSTER("Monster", "monsterenergy.com", "Beverages"),
    GUCCI("Gucci", "gucci.com", "Fashion"),
    PRADA("Prada", "prada.com", "Fashion"),
    LOUIS_VUITTON("Louis Vuitton", "louisvuitton.com", "Fashion"),
    ZARA("Zara", "zara.com", "Fashion"),
    H_M("H&M", "hm.com", "Fashion"),
    UNIQLO("Uniqlo", "uniqlo.com", "Fashion"),
    IKEA("IKEA", "ikea.com", "Retail"),
    WALMART("Walmart", "walmart.com", "Retail"),
    TARGET("Target", "target.com", "Retail"),
    COSTCO("Costco", "costco.com", "Retail"),
    HOME_DEPOT("Home Depot", "homedepot.com", "Retail"),
    BEST_BUY("Best Buy", "bestbuy.com", "Retail"),
    CVS("CVS", "cvs.com", "Healthcare"),
    WALGREENS("Walgreens", "walgreens.com", "Healthcare"),
    LOWES("Lowe's", "lowes.com", "Retail"),
    SHELL("Shell", "shell.com", "Energy"),
    EXXON_MOBIL("ExxonMobil", "exxonmobil.com", "Energy"),
    BP("BP", "bp.com", "Energy"),
    CHEVRON("Chevron", "chevron.com", "Energy"),
    TOTAL("Total", "total.com", "Energy"),
    ARAMCO("Saudi Aramco", "aramco.com", "Energy"),
    ALPHABET("Alphabet", "abc.xyz", "Technology"),
    ORACLE("Oracle", "oracle.com", "Technology"),
    SAP("SAP", "sap.com", "Technology"),
    ADOBE("Adobe", "adobe.com", "Technology"),
    SALESFORCE("Salesforce", "salesforce.com", "Technology"),
    TENCENT("Tencent", "tencent.com", "Technology"),
    BYTEDANCE("ByteDance", "bytedance.com", "Technology"),
    BAIDU("Baidu", "baidu.com", "Technology"),
    ALIBABA("Alibaba", "alibaba.com", "E-commerce"),
    JD("JD.com", "jd.com", "E-commerce"),
    EBAY("eBay", "ebay.com", "E-commerce"),
    SHOPIFY("Shopify", "shopify.com", "E-commerce"),
    RAKUTEN("Rakuten", "rakuten.com", "E-commerce"),
    FLIPKART("Flipkart", "flipkart.com", "E-commerce"),
    WALGREENS_BOOTS("Walgreens Boots Alliance", "walgreensbootsalliance.com", "Healthcare"),
    CVS_HEALTH("CVS Health", "cvshealth.com", "Healthcare"),
    ABBOTT("Abbott Laboratories", "abbott.com", "Healthcare"),
    ROCHE("Roche", "roche.com", "Pharmaceuticals"),
    SANOFI("Sanofi", "sanofi.com", "Pharmaceuticals"),
    BAYER("Bayer", "bayer.com", "Pharmaceuticals"),
    BRISTOL_MYERS("Bristol-Myers Squibb", "bms.com", "Pharmaceuticals"),
    AMGEN("Amgen", "amgen.com", "Pharmaceuticals"),
    REGENERON("Regeneron", "regeneron.com", "Pharmaceuticals"),
    BIOGEN("Biogen", "biogen.com", "Pharmaceuticals"),
    BLACKROCK("BlackRock", "blackrock.com", "Finance"),
    GOLDMAN_SACHS("Goldman Sachs", "goldmansachs.com", "Finance"),
    JPMORGAN("JPMorgan Chase", "jpmorganchase.com", "Finance"),
    MORGAN_STANLEY("Morgan Stanley", "morganstanley.com", "Finance"),
    WELLS_FARGO("Wells Fargo", "wellsfargo.com", "Finance"),
    BANK_OF_AMERICA("Bank of America", "bankofamerica.com", "Finance"),
    CITI("Citigroup", "citi.com", "Finance"),
    BARCLAYS("Barclays", "barclays.com", "Finance"),
    HSBC("HSBC", "hsbc.com", "Finance"),
    DEUTSCHE_BANK("Deutsche Bank", "db.com", "Finance"),
    UBS("UBS", "ubs.com", "Finance"),
    CREDIT_SUISSE("Credit Suisse", "credit-suisse.com", "Finance"),
    SOFI("SoFi", "sofi.com", "Finance"),
    ROBINHOOD("Robinhood", "robinhood.com", "Finance"),
    COINBASE("Coinbase", "coinbase.com", "Cryptocurrency"),
    BINANCE("Binance", "binance.com", "Cryptocurrency"),
    KRAKEN("Kraken", "kraken.com", "Cryptocurrency"),
    OPENSEA("OpenSea", "opensea.io", "Cryptocurrency"),
    RIOT_GAMES("Riot Games", "riotgames.com", "Gaming"),
    ACTIVISION("Activision Blizzard", "activisionblizzard.com", "Gaming"),
    UBISOFT("Ubisoft", "ubisoft.com", "Gaming"),
    ELECTRONIC_ARTS("Electronic Arts", "ea.com", "Gaming"),
    SONY_PLAYSTATION("Sony PlayStation", "playstation.com", "Gaming"),
    NINTENDO("Nintendo", "nintendo.com", "Gaming"),
    SEGA("SEGA", "sega.com", "Gaming"),
    EPIC_GAMES("Epic Games", "epicgames.com", "Gaming"),
    VALVE("Valve", "valvesoftware.com", "Gaming"),
    STEAM("Steam", "store.steampowered.com", "Gaming"),
    PARADOX("Paradox Interactive", "paradoxinteractive.com", "Gaming"),
    CD_PROJEKT("CD Projekt", "cdprojekt.com", "Gaming"),
    TSMC("TSMC", "tsmc.com", "Semiconductors"),
    ARM("ARM", "arm.com", "Semiconductors"),
    BROADCOM("Broadcom", "broadcom.com", "Semiconductors"),
    TEXAS_INSTRUMENTS("Texas Instruments", "ti.com", "Semiconductors"),
    ST_MICROELECTRONICS("STMicroelectronics", "st.com", "Semiconductors"),
    INFINEON("Infineon", "infineon.com", "Semiconductors"),
    MICROCHIP("Microchip Technology", "microchip.com", "Semiconductors"),
    WESTERN_DIGITAL("Western Digital", "westerndigital.com", "Data Storage"),
    SEAGATE("Seagate", "seagate.com", "Data Storage"),
    KINGSTON("Kingston Technology", "kingston.com", "Data Storage"),
    SANDISK("SanDisk", "sandisk.com", "Data Storage"),
    DROPBOX("Dropbox", "dropbox.com", "Data Storage"),
    BOX("Box", "box.com", "Data Storage"),
    ZOOM("Zoom", "zoom.us", "Networking"),
    SLACK("Slack", "slack.com", "Networking"),
    SKYPE("Skype", "skype.com", "Networking"),
    CISCO("Cisco", "cisco.com", "Networking"),
    NOKIA("Nokia", "nokia.com", "Networking"),
    ERICSSON("Ericsson", "ericsson.com", "Networking"),
    VERIZON("Verizon", "verizon.com", "Telecom"),
    AT_T("AT&T", "att.com", "Telecom"),
    T_MOBILE("T-Mobile", "t-mobile.com", "Telecom"),
    VODAFONE("Vodafone", "vodafone.com", "Telecom"),
    ORANGE("Orange", "orange.com", "Telecom"),
    DELOITTE("Deloitte", "deloitte.com", "Consulting"),
    EY("Ernst & Young", "ey.com", "Consulting"),
    KPMG("KPMG", "kpmg.com", "Consulting"),
    PWC("PwC", "pwc.com", "Consulting"),
    BCG("Boston Consulting Group", "bcg.com", "Consulting"),
    MCKINSEY("McKinsey & Company", "mckinsey.com", "Consulting"),
    BAIN("Bain & Company", "bain.com", "Consulting"),
    SPECTRUM("Spectrum", "spectrum.com", "Telecom"),
    HERSHEY("Hershey", "hersheys.com", "Food"),
    MARS("Mars", "mars.com", "Food"),
    FERRERO("Ferrero", "ferrero.com", "Food"),
    KELLOGG("Kellogg's", "kelloggs.com", "Food"),
    GENERAL_MILLS("General Mills", "generalmills.com", "Food"),
    ZALANDO("Zalando", "zalando.com", "E-commerce"),
    REDDIT("Reddit", "reddit.com", "Social Media"),
    DISCORD("Discord", "discord.com", "Social Media"),
    FORD("Ford", "ford.com", "Automotive"),
    NISSAN("Nissan", "nissan.com", "Automotive"),
    HONDA("Honda", "honda.com", "Automotive"),
    HULU("Hulu", "hulu.com", "Entertainment"),
    HBO("HBO", "hbo.com", "Entertainment"),
    PARAMOUNT("Paramount", "paramount.com", "Entertainment"),
    APPLE_MUSIC("Apple Music", "music.apple.com", "Entertainment"),
    AMAZON_PRIME("Amazon Prime", "primevideo.com", "Entertainment"),
    VERSACE("Versace", "versace.com", "Fashion"),
    MARRIOTT("Marriott", "marriott.com", "Hospitality"),
    HILTON("Hilton", "hilton.com", "Hospitality"),
    HYATT("Hyatt", "hyatt.com", "Hospitality"),
    RADISSON("Radisson", "radisson.com", "Hospitality"),
    INTERCONTINENTAL("InterContinental", "ihg.com", "Hospitality"),
    ACCOR("Accor", "group.accor.com", "Hospitality"),
    WYNDHAM("Wyndham", "wyndhamhotels.com", "Hospitality"),
    FOUR_SEASONS("Four Seasons", "fourseasons.com", "Hospitality"),
    CHOICE_HOTELS("Choice Hotels", "choicehotels.com", "Hospitality"),
    RITZ_CARLTON("Ritz-Carlton", "ritzcarlton.com", "Hospitality"),
    DOMINOS("Domino's", "dominos.com", "Food & Beverage"),
    SUBWAY("Subway", "subway.com", "Food & Beverage"),
    PIZZA_HUT("Pizza Hut", "pizzahut.com", "Food & Beverage"),
    STARBUCKS_FOOD("Starbucks Food", "starbucks.com", "Food & Beverage"),
    TACO_BELL("Taco Bell", "tacobell.com", "Food & Beverage"),
    DUNKIN("Dunkin'", "dunkindonuts.com", "Food & Beverage"),
    TRIPADVISOR("Tripadvisor", "tripadvisor.com", "Travel"),
    KAYAK("Kayak", "kayak.com", "Travel"),
    TRIVAGO("Trivago", "trivago.com", "Travel"),
    ORBITZ("Orbitz", "orbitz.com", "Travel"),
    HOTELS("Hotels", "hotels.com", "Travel"),
    PRICELINE("Priceline", "priceline.com", "Travel"),
    VRBO("Vrbo", "vrbo.com", "Travel"),
    BOEING("Boeing", "boeing.com", "Aviation"),
    AIRBUS("Airbus", "airbus.com", "Aviation"),
    EMBRAER("Embraer", "embraer.com", "Aviation"),
    LOCKHEED_MARTIN("Lockheed Martin", "lockheedmartin.com", "Aviation"),
    NORTHROP_GRUMMAN("Northrop Grumman", "northropgrumman.com", "Aviation"),
    RAYTHEON("Raytheon", "raytheon.com", "Aviation"),
    UNITED_AIRLINES("United Airlines", "united.com", "Aviation"),
    CATERPILLAR("Caterpillar", "caterpillar.com", "Industrial"),
    JOHN_DEERE("John Deere", "deere.com", "Industrial"),
    THREE_M("3M", "3m.com", "Industrial"),
    SIEMENS("Siemens", "siemens.com", "Industrial"),
    HONEYWELL("Honeywell", "honeywell.com", "Industrial"),
    BOSCH("Bosch", "bosch.com", "Industrial"),
    SCHNEIDER("Schneider Electric", "se.com", "Industrial"),
    DASSAULT("Dassault Systèmes", "dassaultsystemes.com", "Industrial"),
    FANUC("FANUC", "fanuc.com", "Industrial"),
    ABB("ABB", "abb.com", "Industrial"),
    JOHNSON_AND_JOHNSON("Johnson & Johnson", "jnj.com", "Healthcare"),
    TOTAL_ENERGIES("TotalEnergies", "totalenergies.com", "Energy"),
    BITCOIN("Bitcoin", "bitcoin.org", "Cryptocurrency"),
    ETHEREUM("Ethereum", "ethereum.org", "Cryptocurrency"),
    RIPPLE("Ripple", "ripple.com", "Cryptocurrency"),
    CARDANO("Cardano", "cardano.org", "Cryptocurrency"),
    POLKADOT("Polkadot", "polkadot.network", "Cryptocurrency"),
    TROPICANA("Tropicana", "tropicana.com", "Beverages"),
    GATORADE("Gatorade", "gatorade.com", "Beverages"),
    DR_PEPPER("Dr Pepper", "drpepper.com", "Beverages"),
    MACY("Macy's", "macys.com", "Retail"),
    BESTBUY("Best Buy", "bestbuy.com", "Retail"),
    TOSHIBA("Toshiba", "toshiba.com", "Data Storage"),
    ARISTA("Arista Networks", "arista.com", "Networking"),
    JUNIPER("Juniper Networks", "juniper.net", "Networking"),
    NETGEAR("Netgear", "netgear.com", "Networking"),
    LINKSYS("Linksys", "linksys.com", "Networking"),
    DELL_NETWORKING("Dell Networking", "dell.com", "Networking"),
    SPRINT("Sprint", "sprint.com", "Telecom"),
    PROCTER_AND_GAMBLE("Procter & Gamble", "pg.com", "Consumer Goods"),
    UNILEVER("Unilever", "unilever.com", "Consumer Goods"),
    KIMBERLY_CLARK("Kimberly-Clark", "kimberly-clark.com", "Consumer Goods"),
    COLGATE_PALMOLIVE("Colgate-Palmolive", "colgate.com", "Consumer Goods"),
    HENKEL("Henkel", "henkel.com", "Consumer Goods"),
    RECKITT("Reckitt", "reckitt.com", "Consumer Goods"),
    LOREAL("L'Oréal", "loreal.com", "Consumer Goods"),
    CLOROX("Clorox", "clorox.com", "Consumer Goods"),
    JOHNSON_PRODUCTS("Johnson's", "johnsonsbaby.com", "Consumer Goods"),
    NESTLE("Nestlé", "nestle.com", "Consumer Goods"),
    WAYFAIR("Wayfair", "wayfair.com", "E-commerce"),
    ASOS("ASOS", "asos.com", "E-commerce"),
    JD_COM("JD.com", "jd.com", "E-commerce"),
    WECHAT("WeChat", "wechat.com", "Social Media"),
    VOLKSWAGEN("Volkswagen", "volkswagen.com", "Automotive"),
    BURBERRY("Burberry", "burberry.com", "Fashion"),
    HEINEKEN("Heineken", "heineken.com", "Beverages"),
    CORONA("Corona", "corona.com", "Beverages"),
    JACK_DANIELS("Jack Daniel's", "jackdaniels.com", "Beverages"),
    PERRIER("Perrier", "perrier.com", "Beverages"),
    NESTEA("Nestea", "nestea.com", "Beverages"),
    WENDYS("Wendy's", "wendys.com", "Food & Beverage"),
    EMIRATES("Emirates", "emirates.com", "Aviation"),
    CONOCOPHILLIPS("ConocoPhillips", "conocophillips.com", "Energy"),
    TOTALENERGIES("TotalEnergies", "totalenergies.com", "Energy"),
    ENI("ENI", "eni.com", "Energy"),
    REPSOL("Repsol", "repsol.com", "Energy"),
    BITSTAMP("Bitstamp", "bitstamp.net", "Cryptocurrency"),
    HUOBI("Huobi", "huobi.com", "Cryptocurrency"),
    GEMINI("Gemini", "gemini.com", "Cryptocurrency"),
    MICRON("Micron", "micron.com", "Semiconductors"),
    MEDIATEK("MediaTek", "mediatek.com", "Semiconductors"),
    STMICROELECTRONICS("STMicroelectronics", "st.com", "Semiconductors"),
    LACIE("LaCie", "lacie.com", "Data Storage"),
    CRUCIAL("Crucial", "crucial.com", "Data Storage"),
    KINGMAX("Kingmax", "kingmax.com", "Data Storage"),
    TEAMGROUP("TeamGroup", "teamgroupinc.com", "Data Storage"),
    ADATA("ADATA", "adata.com", "Data Storage"),
    CHINA_MOBILE("China Mobile", "chinamobileltd.com", "Telecom"),
    TELEFONICA("Telefónica", "telefonica.com", "Telecom"),
    BT_GROUP("BT Group", "bt.com", "Telecom"),
    ROGERS("Rogers Communications", "rogers.com", "Telecom"),
    SINGTEL("Singtel", "singtel.com", "Telecom"),
    ACCENTURE("Accenture", "accenture.com", "Consulting"),
    DISNEY_PLUS("Disney+", "disneyplus.com", "Entertainment"),
    SONY_PICTURES("Sony Pictures", "sonypictures.com", "Entertainment"),
    HERMES("Hermès", "hermes.com", "Fashion"),
    QATAR_AIRWAYS("Qatar Airways", "qatarairways.com", "Aviation"),
    CIGNA("Cigna", "cigna.com", "Healthcare"),
    UNITED_HEALTH("UnitedHealth", "uhc.com", "Healthcare"),
    BBIGCOMMERCE("BigCommerce", "bigcommerce.com", "E-commerce"),
    VERO("Vero", "vero.co", "Social Media"),
    MASTODON("Mastodon", "mastodon.social", "Social Media"),
    RIVIAN("Rivian", "rivian.com", "Automotive"),
    LUCID_MOTORS("Lucid Motors", "lucidmotors.com", "Automotive"),
    CRUNCHYROLL("Crunchyroll", "crunchyroll.com", "Entertainment"),
    FUNIMATION("Funimation", "funimation.com", "Entertainment"),
    LETTERBOXD("Letterboxd", "letterboxd.com", "Entertainment"),
    EVERLANE("Everlane", "everlane.com", "Fashion"),
    RODARTE("Rodarte", "rodarte.net", "Fashion"),
    TIM_HORTONS("Tim Hortons", "timhortons.com", "Food & Beverage"),
    NABISCO("Nabisco", "nabisco.com", "Food & Beverage"),
    HOPPER("Hopper", "hopper.com", "Travel"),
    BAXTER("Baxter", "baxter.com", "Healthcare"),
    GILEAD_SCIENCES("Gilead Sciences", "gilead.com", "Healthcare"),
    VERTEX_PHARMA("Vertex Pharmaceuticals", "vrtx.com", "Healthcare"),
    ZULILY("Zulily", "zulily.com", "Retail"),
    THREDUP("ThredUp", "thredup.com", "Retail"),
    GLOBALFOUNDRIES("GlobalFoundries", "globalfoundries.com", "Semiconductors"),
    ARISTA_NETWORKS("Arista Networks", "arista.com", "Networking"),
    UBIQUITI("Ubiquiti", "ui.com", "Networking"),
    LEK("LEK Consulting", "lek.com", "Consulting"),
    MERCER("Mercer", "mercer.com", "Consulting")
    ;

    companion object {

        fun getCategories(): List<String> {
            return entries.map { it.category }.distinct()
        }
    }
}

data class QuestionCompany(
    val correctCompany: Company,
    val options: List<Company>
)